load("@rules_python//python:defs.bzl", "py_library")

package(
    default_visibility = ["//visibility:public"],
)

py_library(
    name = "interop",
    srcs = ["__init__.py"],
    deps = ["//generative_computing/python/interop/langchain"],
)
