load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "interop",
    srcs = ["__init__.py"],
    visibility = [
        "//generative_computing:__subpackages__",
    ],
    deps = ["//generative_computing/python/interop/langchain"],
)
