package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

cc_library(
    name = "read_file",
    srcs = ["read_file.cc"],
    hdrs = ["read_file.h"],
    deps = ["@com_google_absl//absl/strings"],
)
