package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

java_library(
    name = "default_executor",
    srcs = ["DefaultExecutor.java"],
    deps = ["//genc/java/src/java/org/genc/examples/executors/jni"],
)
