package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

java_library(
    name = "default_executor",
    srcs = ["DefaultExecutor.java"],
    data = ["//genc/java/src/native/org/genc/examples/executors:libdefault_executor_jni.so"],
)
