# Java API for generative computing.

package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

# TODO(b/295041820): Figure out how to include actual java_library rules with the android
# constraints.
exports_files(
    srcs = [
        "Executor.java",
        "OwnedValueId.java",
        "Runner.java",
        "ValueId.java",
    ],
    visibility = ["//visibility:public"],
)
