package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

cc_library(
    name = "computation_utils",
    srcs = ["computation_utils.cc"],
    hdrs = ["computation_utils.h"],
    deps = [
        "//generative_computing/cc/intrinsics:intrinsic_uris",
        "//generative_computing/proto/v0:computation_cc_proto",
        "@com_google_absl//absl/strings",
    ],
)
