# TODO(rohanj): describe this package.

package(
    default_visibility = ["//visibility:public"],
)

package_group(
    name = "java_packages",
    packages = ["//generative_computing/java/..."],
)

licenses(["notice"])
